# Generated by Django 4.0.3 on 2022-05-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('text', models.CharField(max_length=150)),
                ('done', models.BooleanField(default=False)),
                ('listId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='taskManagerApp.list')),
            ],
        ),
    ]
