# Generated by Django 4.0.3 on 2023-03-22 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='userId',
            new_name='creatorId',
        ),
        migrations.AddField(
            model_name='project',
            name='usersId',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
