# Generated by Django 4.0.3 on 2022-08-31 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
    ]
