# Generated by Django 4.0.3 on 2022-08-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagerApp', '0002_rename_project_title_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
