# Generated by Django 4.0.3 on 2023-03-22 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManagerApp', '0003_alter_project_usersid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='usersId',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
