# Generated by Django 4.0.3 on 2023-03-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagerApp', '0005_remove_project_creatorid_alter_project_usersid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='usersId',
            new_name='users',
        ),
    ]
